### ISSUE TITLE
cannot handle dotted pair (bug?)

### ISSUE THREAD

**Issue by jsulmont** [mbrezu/cl-messagepack#22]
Hello

Thanks for this library, which I am using for [cl-transit](https://github.com/jsulmont/cl-transit).

Surprisingly the library cannot handle dotted pairs (as it'll try to call `length` on the CDR)...

```lisp
(mpk:encode '(1 . 2))
```

is this something wanted?
Happy to work a PR  -- let me know!

Cheers

**Comment by phmarek** [comment]
Well, the README says

	### Earlier implementation of CL-MESSAGEPACK

	The previous version used the bytes `#xC4`, `#xC5`, `#xC6`, and `#xC7` to encode
	a 'pure' cons (a cons whose `CDR` is not a cons),
	symbols, symbols as a number (via a lookup table), and rationals.

	As these encodings are no longer allowed by the MSGPACK specification this
	functionality has been removed; you can use `*EXTENDED-TYPES*`
	to achieve similar things, though.

**Comment by jsulmont** [comment]
Thanks @phmarek 
I've changed my code to convert dotted pairs to list ..  👍🏻

**Comment by phmarek** [comment]
Ack. Thanks!
