### ISSUE TITLE
Does not build for me - symbol issue

### ISSUE THREAD

**Issue by quicklisp** [mbrezu/cl-messagepack#4]
I get this:

    ; caught ERROR:
    ;   READ error during COMPILE-FILE: The symbol "ID" is not external in the MESSAGEPACK package.

Longer log here: http://report.quicklisp.org/2015-01-20/failure-report/cl-messagepack.html

**Comment by mbrezu** [comment]
@phmarek, is this fixed now? Thanks, miron

**Comment by phmarek** [comment]
Yeah, my tests were successful.
